FROM python:3.11.5-slim-bullseye

WORKDIR /app

# Copia archivos
COPY src/ ./src/

# Instala dependencias Python
RUN pip install --no-cache-dir -r src/requirements.txt

EXPOSE 8050

CMD ["gunicorn", "-b", "0.0.0.0:8050", "src.app_dash:server"]
